title:               The writing of Martin Brennan
include:             ['_pages']
exclude:             ['_includes/notes_graph.json']
description: > # this means to ignore newlines until "baseurl:"
  I’m Martin Brennan, a Software Engineer by day, and a writer whenever I can wrangle it. Genre fiction is my domain — I enjoy writing horror, sci-fi, fantasy, western, and everything else in-between, first in longhand, then typed into the devil-machine. I take cues from every place.
# You may need to change the base URL depending on your deploy configuration.
# Specifically, when using GitHub Pages, the baseurl should point to where GitHub
# Pages deploys your repository (which is usually the repository name).
baseurl:             ''

# If you are using a host that cannot resolve URLs that do
# not end with .html (such as Neocities), set this to 'true'.
use_html_extension:  false

# Set to `true` to open non-internal links in new tabs, or
# set to `false` to open non-internal links in current tab.
open_external_links_in_new_tab: true

# Set to `true` to replace tweet URLs with Twitter embeds.
# Note that doing so will negatively the reader's privacy
# as their browser will communicate with Twitter's servers.
embed_tweets: true

url: "http://writing.martin-brennan.com" # the base hostname & protocol for your site
twitter_username: mjrbrennan
github_username:  martin-brennan
twitter:
  username: mjrbrennan

permalink: pretty
relative_permalinks: false

plugins:
  - jekyll-seo-tag

sass:
  sass_dir:          _sass
  style:            :compressed

collections:
  notes:
    output: true
    permalink: /:slug/

defaults:
  - scope:
      path: "**/*"
    values:
      layout: "default"
  - scope:
      path: "_notes/**/*.md"
    values:
      layout: "note"
  - scope:
      path: "_notes/blog/*.md"
    values:
      layout: "note"
