# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Writing of Martin Brennan
email: martin_brennan@fastmail.com
description: > # this means to ignore newlines until "baseurl:"
  I’m Martin Brennan. I'm a software developer by day, and I like to think I know how to write. Like how a hobo thinks he knows the recipe to Coca-Cola. The authors that inspire me are Cormac McCarthy (my God), Stephen King (my Prophet), J. R. R. Tolkien, George R. R. Martin, Hunter S. Thompson, George Orwell, John Steinbeck, and Kurt Vonnegut.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://writing.martin-brennan.com" # the base hostname & protocol for your site
twitter_username: mjrbrennan
github_username:  martin-brennan

# Build settings
markdown: kramdown
permalink: /:title

gems:
  - jekyll-seo-tag
  - jekyll-paginate
twitter:
  username: mjrbrennan
author: mjrbrennan
comments: true
excerpt_separator: <!--more-->
paginate: 3
future: true
scope:
  path: "_drafts"
  values:
    sitemap: false