on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  run_pull:
    name: publish to website
    runs-on: ubuntu-latest
    
    steps:
    - name: install ssh keys
      # based on https://www.programonaut.com/how-to-deploy-a-git-repository-to-a-server-using-github-actions/
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
    - name: clone
      run: git clone --depth=1 git@github.com:martin-brennan/writing.martin-brennan.com.git writing && cd writing
    - name: add remote
      run: git remote add droplet ${{ secrets.SSH_DROPLET_REMOTE }}
    - name: push to remote
      run: git push droplet main
    - name: cleanup
      run: rm -rf ~/.ssh
