on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  run_pull:
    name: publish to website
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: install ssh keys
      # based on https://www.programonaut.com/how-to-deploy-a-git-repository-to-a-server-using-github-actions/
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
        ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
    - name: git push
      run: |
        cd $GITHUB_WORKSPACE
        git remote add droplet ${{ secrets.SSH_DROPLET_REMOTE }}
        git push droplet main
    - name: cleanup
      run: rm -rf ~/.ssh
